version: 2
jobs:
  build:
    working_directory: ~/looyas_user_managemant_firstinstance_Front
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: |
             npm install
             npm audit fix
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: yarn ng -- build --prod --aot --no-progress
      - run:
          name: angular-test
          command: yarn test -- --single-run --no-progress
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - run:
          name: angular-lint
          command: yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - store_artifacts:
          path: tslint.xml
          prefix: lint
